//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MamsdsTimer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public double WindowHeight {
            get {
                return ((double)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double WindowWidth {
            get {
                return ((double)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BGPPath {
            get {
                return ((string)(this["BGPPath"]));
            }
            set {
                this["BGPPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double WindowLeft {
            get {
                return ((double)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double WindowTop {
            get {
                return ((double)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAutoStart {
            get {
                return ((bool)(this["IsAutoStart"]));
            }
            set {
                this["IsAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTopMost {
            get {
                return ((bool)(this["IsTopMost"]));
            }
            set {
                this["IsTopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<FlowDocument PagePadding=""5,0,5,0"" AllowDrop=""True"" xmlns=""http://schemas.microsoft.com/winfx/2006/xaml/presentation""><Paragraph Margin=""0,0,0,0"" TextAlignment=""Center"" FontFamily=""Times New Roman"" FontSize=""12""><Span FontFamily=""微软雅黑"" FontWeight=""Bold"" FontSize=""26.6666666666667"" Foreground=""#FF000000"" xml:lang=""zh-cn"">现在距离</Span><Run FontFamily=""楷体"" FontWeight=""Bold"" FontSize=""64"" Foreground=""#FF0DA1DF"" xml:lang=""zh-cn"">哆啦A梦</Run><Span FontFamily=""微软雅黑"" FontWeight=""Bold"" FontSize=""26.6666666666667"" Foreground=""#FF000000"" xml:lang=""zh-cn"">出生还有：</Span></Paragraph><Paragraph Margin=""0,0,0,0"" TextAlignment=""Center"" FontFamily=""Times New Roman"" FontSize=""12""><Run FontFamily=""微软雅黑"" xml:lang=""zh-cn"">（哆啦</Run><Span FontFamily=""微软雅黑"" Foreground=""#FF000000"" xml:lang=""zh-cn"">A</Span><Span FontFamily=""微软雅黑"" Foreground=""#FF000000"" xml:lang=""zh-cn"">梦是</Span><Span FontFamily=""微软雅黑"" Foreground=""#FF000000"" xml:lang=""zh-cn"">2112</Span><Span FontFamily=""微软雅黑"" Foreground=""#FF000000"" xml:lang=""zh-cn"">年</Span><Span FontFamily=""微软雅黑"" Foreground=""#FF000000"" xml:lang=""zh-cn"">9</Span><Span FontFamily=""微软雅黑"" Foreground=""#FF000000"" xml:lang=""zh-cn"">月</Span><Span FontFamily=""微软雅黑"" Foreground=""#FF000000"" xml:lang=""zh-cn"">3</Span><Run FontFamily=""微软雅黑"" xml:lang=""zh-cn"">日出生，穿越回20世纪的哦！）</Run></Paragraph></FlowDocument>")]
        public string MainTitleContent {
            get {
                return ((string)(this["MainTitleContent"]));
            }
            set {
                this["MainTitleContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CenterScreen")]
        public global::System.Windows.WindowStartupLocation WindowStartupLocation {
            get {
                return ((global::System.Windows.WindowStartupLocation)(this["WindowStartupLocation"]));
            }
            set {
                this["WindowStartupLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDropShadowEffectEnabled {
            get {
                return ((bool)(this["IsDropShadowEffectEnabled"]));
            }
            set {
                this["IsDropShadowEffectEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OSInstallationSign {
            get {
                return ((string)(this["OSInstallationSign"]));
            }
            set {
                this["OSInstallationSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-12-21")]
        public global::System.DateTime InstallationDate {
            get {
                return ((global::System.DateTime)(this["InstallationDate"]));
            }
            set {
                this["InstallationDate"] = value;
            }
        }
    }
}
